# Generated by Django 2.1.1 on 2018-10-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastaMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_type', models.CharField(choices=[('PZA', 'Pizza'), ('SUB', 'Sub'), ('PTA', 'Sub'), ('SAL', 'Salad'), ('PLT', 'Platter')], default='PZA', max_length=3)),
                ('item_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PizzaMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_type', models.CharField(choices=[('PZA', 'Pizza'), ('SUB', 'Sub'), ('PTA', 'Sub'), ('SAL', 'Salad'), ('PLT', 'Platter')], default='PZA', max_length=3)),
                ('item_name', models.CharField(choices=[('RGL', 'Regular'), ('SCL', 'Sicilian')], default='RGL', max_length=3)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1)),
                ('topping_sel', models.CharField(choices=[('C', 'Cheese'), ('1', '1 topping'), ('2', '2 toppings'), ('3', '3 toppings'), ('S', 'Special')], default='C', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatterMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_type', models.CharField(choices=[('PZA', 'Pizza'), ('SUB', 'Sub'), ('PTA', 'Sub'), ('SAL', 'Salad'), ('PLT', 'Platter')], default='PZA', max_length=3)),
                ('item_name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaladMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_type', models.CharField(choices=[('PZA', 'Pizza'), ('SUB', 'Sub'), ('PTA', 'Sub'), ('SAL', 'Salad'), ('PLT', 'Platter')], default='PZA', max_length=3)),
                ('item_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_type', models.CharField(choices=[('PZA', 'Pizza'), ('SUB', 'Sub'), ('PTA', 'Sub'), ('SAL', 'Salad'), ('PLT', 'Platter')], default='PZA', max_length=3)),
                ('item_name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToppingMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
