# Generated by Django 2.1.1 on 2018-10-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastamenuitem',
            options={'verbose_name': 'Pasta Menu Item'},
        ),
        migrations.AlterModelOptions(
            name='pizzamenuitem',
            options={'verbose_name': 'Pizza Menu Item'},
        ),
        migrations.AlterModelOptions(
            name='plattermenuitem',
            options={'verbose_name': 'Platter Menu Item'},
        ),
        migrations.AlterModelOptions(
            name='saladmenuitem',
            options={'verbose_name': 'Salad Menu Item'},
        ),
        migrations.AlterModelOptions(
            name='submenuitem',
            options={'verbose_name': 'Sub Menu Item'},
        ),
        migrations.AlterModelOptions(
            name='toppingmenuitem',
            options={'verbose_name': 'Topping Menu Item'},
        ),
        migrations.RenameField(
            model_name='toppingmenuitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.AlterField(
            model_name='pastamenuitem',
            name='item_type',
            field=models.CharField(choices=[('PZA', 'Pizza'), ('SUB', 'Sub'), ('PST', 'Pasta'), ('SAL', 'Salad'), ('PLT', 'Platter')], default='PST', max_length=3),
        ),
        migrations.AlterField(
            model_name='pizzamenuitem',
            name='item_name',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], default='Regular', max_length=100),
        ),
        migrations.AlterField(
            model_name='pizzamenuitem',
            name='item_type',
            field=models.CharField(choices=[('PZA', 'Pizza'), ('SUB', 'Sub'), ('PST', 'Pasta'), ('SAL', 'Salad'), ('PLT', 'Platter')], default='PZA', max_length=3),
        ),
        migrations.AlterField(
            model_name='pizzamenuitem',
            name='topping_sel',
            field=models.CharField(choices=[('C', 'Cheese'), ('1', '1 topping'), ('2', '2 toppings'), ('3', '3 toppings'), ('S', 'Special')], default='C', max_length=1, verbose_name='Topping Selection'),
        ),
        migrations.AlterField(
            model_name='plattermenuitem',
            name='item_type',
            field=models.CharField(choices=[('PZA', 'Pizza'), ('SUB', 'Sub'), ('PST', 'Pasta'), ('SAL', 'Salad'), ('PLT', 'Platter')], default='PLT', max_length=3),
        ),
        migrations.AlterField(
            model_name='saladmenuitem',
            name='item_type',
            field=models.CharField(choices=[('PZA', 'Pizza'), ('SUB', 'Sub'), ('PST', 'Pasta'), ('SAL', 'Salad'), ('PLT', 'Platter')], default='SAL', max_length=3),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='item_type',
            field=models.CharField(choices=[('PZA', 'Pizza'), ('SUB', 'Sub'), ('PST', 'Pasta'), ('SAL', 'Salad'), ('PLT', 'Platter')], default='SUB', max_length=3),
        ),
    ]
