# Generated by Django 2.1.1 on 2018-10-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181011_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppingmenuitem',
            name='item_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pizzamenuitem',
            unique_together={('item_type', 'item_name', 'size', 'topping_sel')},
        ),
        migrations.AlterUniqueTogether(
            name='plattermenuitem',
            unique_together={('item_type', 'item_name', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='submenuitem',
            unique_together={('item_type', 'item_name', 'size')},
        ),
    ]
