# Generated by Django 2.1.1 on 2018-10-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181015_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pastamenuitem',
            unique_together={('item_type', 'item_name')},
        ),
        migrations.AlterUniqueTogether(
            name='saladmenuitem',
            unique_together={('item_type', 'item_name')},
        ),
    ]
