# Generated by Django 2.1.2 on 2018-12-30 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20181229_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.MenuItem'),
            preserve_default=False,
        ),
    ]
