# Generated by Django 2.1.2 on 2018-12-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20181230_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='order_status',
            field=models.CharField(choices=[('0', 'In Process'), ('1', 'Order Confirmed')], default='0', max_length=1, verbose_name='Order Status'),
        ),
    ]
