# Generated by Django 2.1.2 on 2018-12-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='comments',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Checked Out'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='add_ons',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='order_status',
            field=models.CharField(choices=[('0', 'In Process'), ('1', 'Checked Out')], default='0', max_length=1, verbose_name='Order Status'),
        ),
    ]
