# Generated by Django 2.1.2 on 2018-12-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20181231_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='conf_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Confirmation #'),
        ),
    ]
